build:
  docker:
    web: Dockerfile

# Optional: specify the stack
stack: heroku-22

# Define the services
services:
  - name: ngrok
    docker:
      image: craxid/rairu-kun
    env:
      PORT: 22
      NGROK_TOKEN: your_ngrok_token
      REGION: your_ngrok_region
