build:
  docker:
    web: Dockerfile

# Optional: specify the stack
stack: heroku-22

# Define the services
services:
  - name: ngrok
    docker:
      image: debian
    env:
      NGROK_TOKEN: your_ngrok_token
      REGION: your_ngrok_region

buildpacks:
  - url: heroku/docker
