build:
  docker:
    web: Dockerfile

# Optional: specify the stack
stack: container

# Define the services
services:
  - name: ngrok
    docker:
      image: debian
    env:
      NGROK_TOKEN: your_ngrok_token
      REGION: false
